spring:
    application:
      serviceId: dinfo-dispatcher
      name: dinfo-dispatcher
    messages:
      encoding: UTF-8
server:
  port: 8899

eureka:
  client:
    service-url:
      defaultZone: http://192.168.191.112:8000/eureka #${eureka.server:http://127.0.0.1:8000/eureka} #注册eureka地址
  instance:
    prefer-ip-address: true
    ip-address: localhost

dinfo:
  dispatcher:
    library:
      path: /tmp/oec8.1/lib/ #自定义组件jar包存放路径
#      tempPath: /Users/yangxuefeng/Documents/temp/